version: '3.9'
services:
  todos-api:
    build:
      context: ../..
      dockerfile: apps/todos-api/Dockerfile
      args:
        APP_NAME: todos-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - blackbox.env
    depends_on:
      - oidc-server-mock

  mocks:
    image: wiremock/wiremock
    ports:
      - 8080:8080

  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      SERVER_OPTIONS_INLINE: |
        {
            "AccessTokenJwtType": "JWT",
            "Discovery": {
                "ShowKeySet": true
            }
        }
      API_SCOPES_INLINE: "[]"
      API_RESOURCES_INLINE: "[]"
      USERS_CONFIGURATION_INLINE: "[]"
      CLIENTS_CONFIGURATION_INLINE: |
        [
            {
                "ClientId": "todos-api-client-id",
                "ClientSecrets": ["todos-api-client-secret"],
                "Description": "todos-api",
                "AllowedGrantTypes": ["client_credentials"],
                "AllowedScopes": [],
                "ClientClaimsPrefix": "",
                "Claims": []
            }
        ]
    ports:
      - 8081:80
