version: '3.9'
services:
  # redis:
  #   image: docker.io/bitnami/redis:6.2
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: 'yes' # recommended only for development.
  #     REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
  #   ports:
  #     - 6379:6379

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   restart: always
  #   ports:
  #     - '8001:8001'

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
